### ISSUE TITLE
Login and Register UI

### ISSUE THREAD

**Issue by Leminhhieu06102311** [Leminhhieu06102311/marketmmo#1]
Làm login và đăng kí phần giao diện cả responsive mobile table và pc

**Comment by AnhTuTran12** [comment]
e sửa lại cái phần responsive rùi á a nma tại vì code từ bản pc rùi mới responsive xuống á a, a xem lại giúp e nếu k được phần nào thì để e sửa, với phần font-size chữ đã sửa ở phần mobile a xem nốt nhé
